### ISSUE TITLE
Is it possible to use jakteristics to detect the differenece of two point clouds?

### ISSUE THREAD

**Issue by 1939938853** [jakarto3d/jakteristics#1]
I mean the operation similar to "subtraction" which can be used for background subtraction or to extract (segment) the changed part of the original point cloud.

Might be relevant to this link? 
https://www.cloudcompare.org/doc/wiki/index.php?title=Distances_Computation 

Thank you

**Comment by davidcaron** [comment]
Hi,

It's not the goal of this library, no. We want this library to focus on a specific task, which is computing features. That said, it's possible that in some cases the features of your point cloud could help you discern some changes that are hard to isolate using only geometric differences.

Like you pointed out, Cloud Compare is very good at computing the se kind of differences between 2 clouds. It also has a command line interface: https://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode I think what you would want is the `C2C_DIST` function.

It would also be possible, and not too complicated to do from python using a kdtree: 
* Create a kdtree using the first cloud
* Interrogate the distance for each point from the second cloud
* Filter points based on your predefined distance threshold
