### ISSUE TITLE
release packaging

### ISSUE THREAD

**Issue by dvolgyes** [jakarto3d/jakteristics#14]
Hi,

First of all: great work and great library!
But as a feature request: currently git has version 0.6.1, pypi 0.6, while the github release contains 0.4.1.
Would it be possible to harmonize them, and all updated to the latest?
(Especially pypi, since very like that's the most frequently used.)

Thank you!

**Comment by davidcaron** [comment]
Hi, thanks for pointing out the issue. The last Github action for 0.6.1 failed and I didn't notice.

Now the git tag, pypi and the github release should be the same, and synchronized by the gibhub action.
