### ISSUE TITLE
features appear a Not a Number

### ISSUE THREAD

**Issue by vinceTapioca** [jakarto3d/jakteristics#4]
Hello,
I'm a beginner.
I installed jackteristics.
The output file is as it follows:
![IMG-20220124-WA0000](https://user-images.githubusercontent.com/98317664/150769309-59e59aee-d42d-49d7-a076-43c1eb693988.jpg)
![nan](https://user-images.githubusercontent.com/98317664/150769314-c17b1490-fc95-40b3-85b1-77dea75797b1.JPG)
![IMG-20220124-WA0001](https://user-images.githubusercontent.com/98317664/150769315-d55f1b74-ee0e-487a-bf1c-ed4007dfa0ce.jpg)
![IMG-20220124-WA0002](https://user-images.githubusercontent.com/98317664/150769317-1f7e580b-9b5e-485e-8266-f39f61042a68.jpg)

Features seems being calculated but output files are not numbers as expected

I really need help.
Thank you in advance

Vince

**Comment by Tofull** [comment]
Hello @vinceTapioca,
Could you share your las file with us ?

**Comment by Tofull** [comment]
@vinceTapioca
We just released a new version of jakteristics which supports recent laspy API updates (library used to read/write las/laz files).
This should solve your issues, especially if you installed jakteristics recently.

Let's try by updating jakteristics package with the following command : 
```sh
python -m pip install --upgrade jakteristics
```

**Comment by vinceTapioca** [comment]
Hello Loic,
I've sent a mail with the new output file.
Thank you for your help
Regards

**Comment by vinceTapioca** [comment]
Hello Loic,
It could be of some help as follows:
I installed on Python original IDLE:
numpy
Cyton
laspy
shipy
typer and jakteristics

I run the module copied:

from jakteristics import las_utils, compute_features, FEATURE_NAMES

input_path = "/path/to/a/las_file.las"
xyz = las_utils.read_las_xyz(input_path)

features = compute_features(xyz, search_radius=0.15)

output_path = "/path/to/output_file.las"
las_utils.write_with_extra_dims(input_path, output_path, features, FEATURE_NAMES)_


NO error messages;
same output file A11F.las I've sent you yesterday.

The binary mismath error with numpy does not pop up any more but it seems numbers are not read (or written) properly.ù

Hope on your help.
Thank you

**Comment by davidcaron** [comment]
What kind of point cloud are you using? Is it aerial? I'm asking because points are usually further apart in an aerial scan, and a radius of 0.15 might not be enough to reach any neighboring point. Try with a radius of 1.0, or check the average distance between your points and use 2x or 3x that value.

**Comment by vinceTapioca** [comment]
Hi  David,
I keep thanking you and Loic,
You got it:
due to scale amplification, coordinates are very big (and the PC not dense) so distances very hight: I put R=1000000000 and obtained  numpy file _**features**_ full of numbers - please find attached the txt file.
Script in jupiter as it follows:
![image](https://user-images.githubusercontent.com/98317664/151564056-0631a127-037b-4c57-9b1e-1a0073a77b01.png)

Unfortunately, though changed ,the .las file (attached) is still not readable.
Its a pity since I have no label to understand numerical values.

Is it possible to be provided with a mask of labels to read the feature.txt?

Best Regards

PS
in case files are to big to be uploaded I'll provide sending them by mail
